#!/bin/sh

document=$1
question=$2
topDir=$PWD

cd AnsweringSystem
python3 InfoRetrieval.py $topDir/$question $topDir/$document
python3 AnsweringMachine.py $topDir/$question ChosenSentences.txt
rm -f ChosenSentence.txt
cd ..